animal = ['bear', 'ruby', 'peacock', 'kangaroo', 'whale', 'platypus']
puts"The animal at 1 = #{animal[0]}"
puts"the animal at 3rd = #{animal[2]}"
puts" the animal at 1st = #{animal[1]}"
puts" the animal at 3 = #{animal[2]}"
puts"the animal at 5th = #{animal[4]}"
puts" the animal at 2 = #{animal[2]}"
puts" the animal at 6th = #{animal[5]}"
puts"the animal at 4 = #{animal[4]}"